### ISSUE TITLE
Readme indicates yarn only needed if editing, but then also says you have to start with yarn start

### ISSUE THREAD

**Issue by sbweeden** [ajcase/CI-SAML-Sample#1]
Can non-yarn-based startup be documented?

**Comment by sbweeden** [comment]
Also related to startup - I tried npm run and got:

```
[nodemon] starting `node ./server-build/index.js`
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '../SAMLkey.key'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at eval (webpack:///./server/index.js?:64:19)
    at Module../server/index.js (/Users/sweeden/git/ajcase/CI-SAML-Sample/server-build/index.js:157:1)
    at __webpack_require__ (/Users/sweeden/git/ajcase/CI-SAML-Sample/server-build/index.js:20:30)
    at /Users/sweeden/git/ajcase/CI-SAML-Sample/server-build/index.js:84:18
    at Object.<anonymous> (/Users/sweeden/git/ajcase/CI-SAML-Sample/server-build/index.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
[nodemon] app crashed - waiting for file changes before starting...
```

I don't know what the default start directory is, but it seems to be something other than a level below the repo root where those files live.

**Comment by jonpharry** [comment]
I removed the `../` from references to `../SAMLkey.key` and `../SAMLCertificate.pem` and I was then able to start the application using either `yarn start` or `npm start`.
